#!/usr/bin/perl

use strict;
use warnings;

use Media::DateTime;
use DateTime;

my $dater = Media::DateTime->new();

for my $file (@ARGV){
	my $dt = $dater->datetime( $file ) or die "couldn't date: $file\n";
	printf "%s: %s\n", $dt, $file;
}

